### ISSUE TITLE
窗口边框的问题

### ISSUE THREAD

**Issue by Webcopy** [kira-96/ExtendedWindow#1]
窗口非最大化的时候，边框的颜色是白色的，如何设置成其它的颜色？多谢！

**Comment by kira-96** [comment]
没想到还有人会用，本来我只打算给自己使用的。
`UniversalWindowStyle`是我从[这里](https://blog.walterlv.com/post/wpf-simulate-native-window-title-bar-buttons)拷贝过来的样式。
我不建议使用`UniversalWindowStyle`，我刚刚看到它的样式有问题
`Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=(0).InactiveForegroundColor;`
会导致标题栏颜色不能正常显示。
我在`demo`里面添加了另一个窗口示例，建议使用`ExtendedWindow`。
可以参考[README](https://github.com/kira-96/ExtendedWindow/blob/master/README.md)里面的几个链接，我都是从那里面拷贝的代码。

**Comment by Webcopy** [comment]
改造需要在win7下跑的旧软件，就找到了这个包装窗口。我去看看你上面给的链接，谢谢。

**Comment by kira-96** [comment]
实际上UniversalWindow的标题栏是和内容放在一起的，这就是为什么要设置`Grid`的`margin=0,32,0,0`，因为需要空出标题栏的高度，标题栏的背景就是Grid的背景。
![Snipaste_2020-05-09_19-50-32](https://user-images.githubusercontent.com/22876709/81472997-5d519500-922e-11ea-8675-665722d6008c.png)
我这里用了一张图像作为背景，可以看到效果非常完美。

**Comment by Webcopy** [comment]
`<Setter Property="WindowChrome.WindowChrome">
            <Setter.Value>
                <WindowChrome GlassFrameThickness="0 64 0 0" NonClientFrameEdges="Left,Bottom,Right" UseAeroCaptionButtons="False" />
            </Setter.Value>
        </Setter>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="Window">
                    <Border Padding="4 1 4 4">`
上面是 UniversalWindow.xaml文件中关于WindowChrome控件的样式设置，把`NonClientFrameEdges="Left,Bottom,Right"`改成`NonClientFrameEdges="None"`再把`<Border Padding="4 1 4 4">`修改成自己需要边框颜色就可以了。比如`<Border Padding="1,1,1,1" Background="Gray">`

这个窗口样式是模仿UWP风格的，你上面的图片背景的窗口非常漂亮。我只是不喜欢窗口四周的四条白边。另外`<Border Padding="4 1 4 4">`这么设置可能是兼顾在win7下运行程序时的样式。

**Comment by kira-96** [comment]
我没在Win7上试过这个窗口样式，Win10上的窗口边框都是根据主题色动态变换的。
另外，我还发现了一个bug，在修改主题色之后，窗体的内容会整体偏移，需要重新刷新显示才能正常显示。
![Snipaste_2020-05-11_09-21-13](https://user-images.githubusercontent.com/22876709/81515980-fa184d80-9368-11ea-9d43-38e2e6bdd494.png)

**Comment by Webcopy** [comment]
我从你这里下载的代码例子，运行的时候，改变主题色后（win10系统的主题）没出现你说的偏移现象啊。

**Comment by kira-96** [comment]
我已经修改过了，就是`NonClientFrameEdges="Left,Bottom,Right"`导致的。
